run_action:
  fields:
    action_type:
      required: true
      example: obs_scene_set
      selector:
        text:
    target:
      example: Home OBS
      selector:
        text:
    value:
      example: Gaming
      selector:
        text:
    action_params:
      example: '{"remember": true}'
      selector:
        object:
    entry_id:
      required: false
      selector:
        config_entry:
          integration: switchboard

obs_scene_set:
  fields:
    target:
      required: true
      example: Home OBS
      selector:
        text:
    scene:
      required: true
      example: Gaming
      selector:
        text:
    entry_id:
      required: false
      selector:
        config_entry:
          integration: switchboard

overlay_alert:
  fields:
    text:
      required: true
      example: Be right back!
      selector:
        text:
    entry_id:
      required: false
      selector:
        config_entry:
          integration: switchboard

set_machine_state:
  fields:
    state:
      required: true
      example: afk
      selector:
        select:
          options:
            - afk
            - active
    entry_id:
      required: false
      selector:
        config_entry:
          integration: switchboard
